### ISSUE TITLE
Suggestion for composing download URL

### ISSUE THREAD

**Issue by tellison** [cilki/jlink.online#3]
Maybe safer to use the `binary/releases` [API](https://api.adoptopenjdk.net/) rather than building the URL directly (in case the storage URL moves)?

https://github.com/cilki/jlink.online/blob/fd35db2d6b1707194e85034ab4849cc6c7ba6e41/jlink.go#L278

**Comment by cilki** [comment]
Agreed :+1:. I can probably do this today or tomorrow.
